service: notification-service

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 1024
  timeout: 10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yml):SendMailIAM}

resources:
  Resources:
    MailQueue: ${file(resources/MailQueue.yml):MailQueue}
  Outputs:
    MailQueueArn: ${file(resources/MailQueue.yml):Outputs.MailQueueArn}
    MailQueueUrl: ${file(resources/MailQueue.yml):Outputs.MailQueueUrl}

functions:
  sendMail:
    handler: src/handlers/sendMail.handler
    events:
      - sqs:
          arn: ${self:custom.mailQueue.arn}
          batchSize: 1

custom:
  mailQueue:
    name: MailQueue-${self:provider.stage}
    arn: !GetAtt MailQueue.Arn
    url: !Ref MailQueue
  webpack:
    webpackConfig: webpack.config.js
    includeModules: true
    packager: 'npm'
    excludeFiles: src/**/*.test.ts


