service: notification-service

plugins:
  - serverless-webpack
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  timeout: 10
  stage: ${opt:stage, 'dev'}
  region: us-east-1
  iamRoleStatements:
    - ${file(iam/SendMailIAM.yml):SendMailIAM}
  
functions:
  sendMail:
    handler: src/handlers/sendMail.handler
